services:
  - type: web
    name: zowt-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: zowt-postgres
          property: connectionString

databases:
  - name: zowt-postgres
    databaseName: zowt
    user: zowt
    plan: free
